// Données de vocabulaire pour l'entraînement d'anglais - Manager SI
const VOCABULARY_DATA = {
  mots: [
    ["Logiciel", "Software"],
    ["Cahier des charges", "Specifications"],
    ["Navigateur", "Browser"],
    ["Moteur de recherche", "Search engine"],
    ["Programmation", "Programming"],
    ["Nom de domaine", "Domain name"],
    ["Compte", "Account"],
    ["Créer un compte", "To sign up"],
    ["Définir un mot de passe", "To set a password"],
    ["Utilisateur", "User"],
    ["Identifiant", "Username"],
    ["Bibliothèque", "Library"],
    ["Cadre de travail", "Framework"],
    [
      "Environnement de développement",
      "Integrated development environment - IDE",
    ],
    ["Maintenance", "Maintenance"],
    ["Sauvegarde", "Backup"],
    ["Base de données", "Database"],
    ["Flux de données", "Data flow"],
    ["Stockage de données", "Data storage"],
    ["Pare-feu", "Firewall"],
    ["Logiciel espion", "Spyware"],
    ["Bande passante", "Bandwidth"],
    ["Interface de programmation", "Application Programming Interface - API"],
    ["Balise", "Markup"],
    ["Langage binaire", "Binary language"],
    ["Système de gestion de contenu", "Content management system - CMS"],
    ["Serveur", "Server / Host"],
    ["Service d'hébergement", "Hosting service"],
    ["Plan de site / Arborescence", "Sitemap"],
    ["Site statique", "Static site"],
    ["Site dynamique", "Dynamic site"],
    ["Site animé", "Animated site"],
    ["Refonte", "Redesign"],
    ["Charte graphique", "Graphic charter"],
    ["Bannière", "Banner"],
    ["Référencement", "Referencing"],
    [
      "Optimisation pour les moteurs de recherche",
      "Search Engine Optimization - SEO",
    ],
    ["Référencement payant", "Search Engine Advertising - SEA"],
    ["Référencement abusif", "Spamdexing"],
    ["Réseau Social", "Social Network"],
    ["Protocole de transfert de fichier", "File Transfer Protocol"],
    ["Transfert de fichier", "File transfer"],
    ["Partage de fichier", "File sharing"],
    ["Télécharger", "To download/To upload"],
    ["Visite virtuelle", "Virtual visit"],
    ["Objet interactif", "Interactive object"],
    ["Interface utilisateur graphique", "Graphic user interface"],
    ["Prototype d'interface utilisateur", "Mock-up"],
    ["Expérience utilisateur", "User experience"],
    ["Maquette fonctionnelle d'un site", "Wireframe"],
    ["Tableau", "Array"],
    ["Chaîne (de caractères)", "String"],
    ["Boucle", "Loop"],
    ["Effectuer / Réaliser", "To perform"],
    ["Traiter", "To process"],
    ["Jalons / Étape clé", "Milestone"],
    ["Ainsi que / De même que", "As well as"],
    ["Impliqué", "Involved"],
    ["Réduire / Restreindre", "To narrow"],
    ["Étendre / Développer", "To expand"],
    ["Efficace", "Efficient"],
    ["Fiable", "Reliable"],
    ["Mener / Réaliser", "To conduct"],
    ["Concevoir / Élaborer", "To design"],
    ["Pérennité", "Sustainability"],
    ["Respecter les délais", "To meet deadlines"],
    ["Améliorer", "To improve"],
    ["Défaut / Anomalie", "Defect"],
    ["Mettre en œuvre", "To implement"],
    ["Diriger / Mener", "To lead"],
    ["Fonctionnalités / Caractéristiques", "Features"],
    ["Attentes", "Expectations"],
  ],
  expressions: [
    [
      "Déclarer une variable en langage java",
      "Declare a variable in java language",
    ],
    [
      "Utiliser des tableaux pour stocker plusieurs valeurs dans une seule variable",
      "Use arrays to store multiple values in a single variable",
    ],
    ["Créer une chaîne en java", "Create a string in java"],
    ["Exécuter des boucles", "Execute loops"],
    [
      "Effectuer une opération d'entrée ou de sortie",
      "Perform an input or output operation",
    ],
    [
      "Traiter une information représentée sous sa forme binaire",
      "Process a binary information",
    ],
    [
      "Comprendre les principaux livrables, les jalons, ainsi que les rôles et les responsabilités",
      "Understand the main deliverables, milestones, as well as the roles and responsibilities",
    ],
    [
      "Utiliser les opérateurs booléens pour réduire, étendre ou affiner les résultats",
      "Use Boolean operators to narrow, expand, or refine search results",
    ],
    [
      "Créer une procédure stockée dans une base de données",
      "Create a stored procedure in a database",
    ],
    [
      "Utiliser les algorithmes les plus efficaces possibles pour résoudre des problèmes",
      "Use the most efficient algorithms possible to solve problems",
    ],
    [
      "Développer des solutions logicielles fiables et fonctionnelles",
      "Develop reliable and functional software solutions",
    ],
    [
      "Se positionner comme expert technique",
      "Position oneself as a technical expert",
    ],
    [
      "Gérer et optimiser la base de données",
      "Manage and optimize the database",
    ],
    ["Réaliser une étude logicielle", "Conduct a software study"],
    [
      "Concevoir l'architecture des applications",
      "Design application architecture",
    ],
    ["Assurer la gestion des données", "Ensure data management"],
    ["Sécuriser les applications", "Secure applications"],
    ["Implémenter des solutions logicielles", "Implement software solutions"],
    ["Créer des programmes", "Build programs"],
    ["Écrire et tester le code", "Write and test code"],
    ["Collaborer avec des développeurs", "Collaborate with developers"],
    ["Utiliser des outils de développement", "Use development tools"],
    ["Créer des applications ergonomiques", "Create ergonomic applications"],
    [
      "Ecouter, analyser et rédiger les besoins",
      "Listen, analyze and write needs",
    ],
    [
      "Être garant de la pérennité et de l'évolution des solutions",
      "To guarantee the sustainability and evolution of solutions",
    ],
    [
      "Respecter les délais, les coûts et la qualité",
      "Meet deadlines, costs and quality",
    ],
    ["Satisfaire les attentes du client", "Meet client expectations"],
    [
      "Piloter une projet d'ingénierie logicielle",
      "Lead a software engineering project",
    ],
    ["Construire un cahier des charges", "Build specifications"],
    ["Gérer les données de l'entreprise", "Manage company data"],
    ["Développer des applications mobiles", "Develop mobile apps"],
    [
      "Accompagner la stratégie de l'entreprise",
      "Support the company's strategy",
    ],
    [
      "Suivre les principes et bonnes pratiques de développement",
      "Follow development principles and best practices",
    ],
    [
      "Analyser et identifier tous les problèmes potentiels",
      "Analyze and identify any potential problems",
    ],
    [
      "Améliorer et maintenir le logiciel à long terme",
      "Improve and maintain the software in the long term",
    ],
    [
      "Traduire le besoin du client en demandes fonctionnelles",
      "Translate the client's need into functional demands",
    ],
    [
      "Analyser et décrire les tâches à réaliser par l'ordinateur",
      "Analyze and describe the tasks to be performed by the computer",
    ],
    [
      "Déterminer et schématiser les fonctionnalités du logiciel",
      "Determine and schematize the software functionalities",
    ],
    ["Déceler les défauts de programmation", "Identify programming defects"],
    ["Effectuer des traitements par lot", "Perform batch processes"],
    [
      "Contrôler les évolutions et les différentes versions du logiciel",
      "Control developments and different versions of the software",
    ],
    [
      "Maintenir en condition opérationnelle le logiciel",
      "Keep the software in operational condition",
    ],
    [
      "Mettre en production à l'issue des phases de qualification",
      "Put into production at the end of the qualification and integration phases",
    ],
    [
      "Rédiger le code source qui constitue le corps du logiciel",
      "Write the source code that forms the body of the software",
    ],
    [
      "Mettre en œuvre l'agilité au sein d'une équipe de développeurs",
      "Implement agility as part of a team of developers",
    ],
    ["Diriger des projets collaboratifs", "Lead collaborative projects"],
    [
      "Vérifier que les fonctions correspondent aux attentes du client",
      "Make sure the features offered by the software are in line with the customer's expectations",
    ],
    [
      "Définir les étapes clés de cycle de vie du projet",
      "Define key lifecycle milestones for the project",
    ],
    [
      "Intégrer les environnements de développement",
      "Integrate development environments",
    ],
    [
      "Gérer les modifications apportées au code source",
      "Manage changes to source code",
    ],
  ],
  definitions: [
    [
      "Technical debt",
      "This concept refers to the failure to comply with the design of software, intentional or not, which entails additional costs in the future.",
    ],
    [
      "Enterprise Resource Planning - ERP",
      "This information system is used to manage and follow all of a company's information and operational services on a daily basis.",
    ],
    [
      "Key success factor",
      "An essential consideration in addressing a market. Each company faces several of these elements that need to be mastered at the risk of not being competitive.",
    ],
    [
      "Unit testing",
      "A procedure to verify the proper functioning of a specific part of a software or portion of a program, also known as component testing.",
    ],
    [
      "Error management",
      "This process brings together the various ways to protect the user from errors and allow them to correct them. The goal is to minimize interruptions due to errors.",
    ],
    [
      "Version management",
      "This process involves managing all versions of one or more files.",
    ],
    [
      "Software pipelining",
      "A technique used by compilers to optimize loop execution.",
    ],
    [
      "Maintainability",
      "In the IT field, the ability for components or applications to be maintained, consistently and at a lower cost, in working order.",
    ],
    [
      "Design pattern",
      "A characteristic module arrangement, recognized as good practice in response to a software design problem. It describes a standard solution that can be used in the design of different software.",
    ],
    [
      "Testing policy",
      "A high-level document outlining the organization's key principles, approaches and objectives regarding testing activity. This document describes why testing is done.",
    ],
    [
      "Database query",
      "A questioning of a database. It may have a number of criteria for specifying the application. There are several query languages, which are specific to the structure of the databases.",
    ],
    [
      "Data visualization",
      "A set of graphical representation methods, in two or three dimensions, using color and frames or not. Computer resources allow complex sets of data to be represented in a simpler, educational and pedagogical way.",
    ],
    [
      "Microservices",
      "A software development technique, a variant of the architectural style of service-oriented architecture, which structures an application as a set of poorly coupled services.",
    ],
    [
      "Platform as a service (Paas)",
      "A cloud service category that offers a processing platform and a software layer as a service.",
    ],
    [
      "Selection criteria",
      "Defining these elements allows you to select the most relevant criteria based on a goal to be achieved.",
    ],
    [
      "Software architecture",
      "This concept is designed with the needs of the future user of the application based on the study and the results of creating an element or functionality of the software that will suit the needs in question.",
    ],
    [
      "Cloud computing",
      "Software or data hosted or launched on remote servers, accessible from anywhere on the internet.",
    ],
    [
      "Pentest",
      "An ethical hacking technique that tests the vulnerability of a computer system, application or website by detecting vulnerabilities that may be exploited by a hacker or malware.",
    ],
    [
      "Security policy",
      "An action plan defined to preserve the integrity and sustainability of a social group.",
    ],
    [
      "Roadmap",
      "This document generally proposes a list of means, the target or targets, principles to follow and values to be respected, the priority of tasks, and a timetable for achieving those goals.",
    ],
    [
      "Arguing to convince",
      "This method supports an assertion using reasoning or evidence.",
    ],
    [
      "Setting up an audit tool",
      "The purpose of implementing this system is to identify and assess the risks (operational, financial, reputational in particular) associated with the IT activities of a company or administration.",
    ],
    [
      "Development improvement",
      "An approach that aims to perfect the programs developed by offering innovative technical solutions.",
    ],
    [
      "Setting up a quality approach",
      "This methodology is all the actions carried out by a company to: improve quality management, offer better products, services to customers, and make employees evolve.",
    ],
    [
      "Matrix of choices",
      "A table that brings together all our choices as well as the different criteria to consider in order to decide between them. This matrix facilitates decision-making because it lets you know which is the best choice through a weighting system.",
    ],
  ],
};
